// Code generated by mockery v2.44.2. DO NOT EDIT.

package componentmocks

import (
	context "context"

	ethclient "github.com/kaleido-io/paladin/kata/pkg/ethclient"
	mock "github.com/stretchr/testify/mock"
)

// ABIFunctionClient is an autogenerated mock type for the ABIFunctionClient type
type ABIFunctionClient struct {
	mock.Mock
}

// R provides a mock function with given fields: ctx
func (_m *ABIFunctionClient) R(ctx context.Context) ethclient.ABIFunctionRequestBuilder {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for R")
	}

	var r0 ethclient.ABIFunctionRequestBuilder
	if rf, ok := ret.Get(0).(func(context.Context) ethclient.ABIFunctionRequestBuilder); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ethclient.ABIFunctionRequestBuilder)
		}
	}

	return r0
}

// NewABIFunctionClient creates a new instance of ABIFunctionClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewABIFunctionClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ABIFunctionClient {
	mock := &ABIFunctionClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
