// Code generated by mockery v2.44.2. DO NOT EDIT.

package componentmocks

import mock "github.com/stretchr/testify/mock"

// DomainActions is an autogenerated mock type for the DomainActions type
type DomainActions struct {
	mock.Mock
}

// NewDomainActions creates a new instance of DomainActions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDomainActions(t interface {
	mock.TestingT
	Cleanup(func())
}) *DomainActions {
	mock := &DomainActions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
