//go:build !reference
// +build !reference

package reference

import (
	"context"
	"os"
	"testing"

	"github.com/hyperledger/firefly-common/pkg/i18n"
	"github.com/kaleido-io/paladin/toolkit/pkg/pldclient"
	"github.com/stretchr/testify/assert"
	"golang.org/x/text/language"
)

func TestCheckGeneratedMarkdownPages(t *testing.T) {
	ctx := i18n.WithLang(context.Background(), language.Spanish)
	markdownMap, err := GenerateObjectsReferenceMarkdown(ctx)
	assert.NoError(t, err)
	assert.NotNil(t, markdownMap)

	for pageName, markdown := range markdownMap {
		b, err := os.ReadFile(pageName)
		assert.NoError(t, err)
		assert.Equal(t, string(b), string(markdown), "The type reference docs generated by the code did not match the docs files in git for page: '%s' Did you forget to run `gradle generateDocs`?", pageName)
	}
}

func TestGenerateMarkdownDescriptionMissing(t *testing.T) {
	type thingy struct{}
	d := newDocGenerator()
	_, err := d.generateMarkdownPages(context.Background(), []interface{}{thingy{}}, []interface{}{}, []pldclient.RPCModule{}, "")
	assert.Regexp(t, "PD020900.*thingy_description.md", err)
}
