// Copyright © 2024 Kaleido, Inc.
//
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build !reference
// +build !reference

package reference

import (
	"context"
	"os"
	"testing"

	"github.com/LF-Decentralized-Trust-labs/paladin/common/go/pkg/i18n"
	"github.com/LF-Decentralized-Trust-labs/paladin/sdk/go/pkg/pldclient"
	"github.com/stretchr/testify/assert"
	"golang.org/x/text/language"
)

func TestCheckGeneratedMarkdownPages(t *testing.T) {
	ctx := i18n.WithLang(context.Background(), language.Spanish)
	markdownMap, err := GenerateObjectsReferenceMarkdown(ctx)
	assert.NoError(t, err)
	assert.NotNil(t, markdownMap)

	for pageName, markdown := range markdownMap {
		b, err := os.ReadFile(pageName)
		assert.NoError(t, err)
		assert.Equal(t, string(b), string(markdown), "The type reference docs generated by the code did not match the docs files in git for page: '%s' Did you forget to run `gradle generateDocs`?", pageName)
	}
}

func TestGenerateMarkdownDescriptionMissing(t *testing.T) {
	type thingy struct{}
	d := newDocGenerator()
	_, err := d.generateMarkdownPages(context.Background(), []interface{}{thingy{}}, []interface{}{}, []pldclient.RPCModule{}, "")
	assert.Regexp(t, "PD020900.*thingy_description.md", err)
}
