// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.1
// source: plugin-interface.proto

package PluginInterface

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaladinMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoutingInformation string `protobuf:"bytes,1,opt,name=routingInformation,proto3" json:"routingInformation,omitempty"`
	MessageContent     string `protobuf:"bytes,2,opt,name=messageContent,proto3" json:"messageContent,omitempty"`
}

func (x *PaladinMessage) Reset() {
	*x = PaladinMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_interface_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaladinMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaladinMessage) ProtoMessage() {}

func (x *PaladinMessage) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_interface_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaladinMessage.ProtoReflect.Descriptor instead.
func (*PaladinMessage) Descriptor() ([]byte, []int) {
	return file_plugin_interface_proto_rawDescGZIP(), []int{0}
}

func (x *PaladinMessage) GetRoutingInformation() string {
	if x != nil {
		return x.RoutingInformation
	}
	return ""
}

func (x *PaladinMessage) GetMessageContent() string {
	if x != nil {
		return x.MessageContent
	}
	return ""
}

type PaladinMessageReceipt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *PaladinMessageReceipt) Reset() {
	*x = PaladinMessageReceipt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_interface_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaladinMessageReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaladinMessageReceipt) ProtoMessage() {}

func (x *PaladinMessageReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_interface_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaladinMessageReceipt.ProtoReflect.Descriptor instead.
func (*PaladinMessageReceipt) Descriptor() ([]byte, []int) {
	return file_plugin_interface_proto_rawDescGZIP(), []int{1}
}

func (x *PaladinMessageReceipt) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_plugin_interface_proto protoreflect.FileDescriptor

var file_plugin_interface_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x22, 0x68, 0x0a, 0x0e, 0x50, 0x61, 0x6c, 0x61, 0x64, 0x69, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x2e, 0x0a, 0x12, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12,
	0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x31, 0x0a, 0x15, 0x50, 0x61,
	0x6c, 0x61, 0x64, 0x69, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x70, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x32, 0x7f, 0x0a,
	0x0f, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x12, 0x6c, 0x0a, 0x11, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x46, 0x6c, 0x6f, 0x77, 0x12, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x50,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x50,
	0x61, 0x6c, 0x61, 0x64, 0x69, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x2d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x50, 0x61, 0x6c, 0x61, 0x64, 0x69, 0x6e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x22, 0x00, 0x42, 0x18,
	0x5a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plugin_interface_proto_rawDescOnce sync.Once
	file_plugin_interface_proto_rawDescData = file_plugin_interface_proto_rawDesc
)

func file_plugin_interface_proto_rawDescGZIP() []byte {
	file_plugin_interface_proto_rawDescOnce.Do(func() {
		file_plugin_interface_proto_rawDescData = protoimpl.X.CompressGZIP(file_plugin_interface_proto_rawDescData)
	})
	return file_plugin_interface_proto_rawDescData
}

var file_plugin_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_plugin_interface_proto_goTypes = []interface{}{
	(*PaladinMessage)(nil),        // 0: protos.PluginInterface.PaladinMessage
	(*PaladinMessageReceipt)(nil), // 1: protos.PluginInterface.PaladinMessageReceipt
}
var file_plugin_interface_proto_depIdxs = []int32{
	0, // 0: protos.PluginInterface.PluginInterface.PluginMessageFlow:input_type -> protos.PluginInterface.PaladinMessage
	1, // 1: protos.PluginInterface.PluginInterface.PluginMessageFlow:output_type -> protos.PluginInterface.PaladinMessageReceipt
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_plugin_interface_proto_init() }
func file_plugin_interface_proto_init() {
	if File_plugin_interface_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_plugin_interface_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaladinMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_interface_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaladinMessageReceipt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plugin_interface_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_interface_proto_goTypes,
		DependencyIndexes: file_plugin_interface_proto_depIdxs,
		MessageInfos:      file_plugin_interface_proto_msgTypes,
	}.Build()
	File_plugin_interface_proto = out.File
	file_plugin_interface_proto_rawDesc = nil
	file_plugin_interface_proto_goTypes = nil
	file_plugin_interface_proto_depIdxs = nil
}
