//
// Copyright © 2024 Kaleido, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: pkg/proto/paladin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaladinGRPCTransport_ConnectSendStream_FullMethodName = "/github.com.kaleido_io.paladin.transports.grpc.PaladinGRPCTransport/ConnectSendStream"
)

// PaladinGRPCTransportClient is the client API for PaladinGRPCTransport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaladinGRPCTransportClient interface {
	// The sender of messages connects a unidirectional stream, and the server should hold it open for us indefinitely.
	ConnectSendStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Message, Empty], error)
}

type paladinGRPCTransportClient struct {
	cc grpc.ClientConnInterface
}

func NewPaladinGRPCTransportClient(cc grpc.ClientConnInterface) PaladinGRPCTransportClient {
	return &paladinGRPCTransportClient{cc}
}

func (c *paladinGRPCTransportClient) ConnectSendStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Message, Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PaladinGRPCTransport_ServiceDesc.Streams[0], PaladinGRPCTransport_ConnectSendStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Message, Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PaladinGRPCTransport_ConnectSendStreamClient = grpc.ClientStreamingClient[Message, Empty]

// PaladinGRPCTransportServer is the server API for PaladinGRPCTransport service.
// All implementations must embed UnimplementedPaladinGRPCTransportServer
// for forward compatibility.
type PaladinGRPCTransportServer interface {
	// The sender of messages connects a unidirectional stream, and the server should hold it open for us indefinitely.
	ConnectSendStream(grpc.ClientStreamingServer[Message, Empty]) error
	mustEmbedUnimplementedPaladinGRPCTransportServer()
}

// UnimplementedPaladinGRPCTransportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaladinGRPCTransportServer struct{}

func (UnimplementedPaladinGRPCTransportServer) ConnectSendStream(grpc.ClientStreamingServer[Message, Empty]) error {
	return status.Errorf(codes.Unimplemented, "method ConnectSendStream not implemented")
}
func (UnimplementedPaladinGRPCTransportServer) mustEmbedUnimplementedPaladinGRPCTransportServer() {}
func (UnimplementedPaladinGRPCTransportServer) testEmbeddedByValue()                              {}

// UnsafePaladinGRPCTransportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaladinGRPCTransportServer will
// result in compilation errors.
type UnsafePaladinGRPCTransportServer interface {
	mustEmbedUnimplementedPaladinGRPCTransportServer()
}

func RegisterPaladinGRPCTransportServer(s grpc.ServiceRegistrar, srv PaladinGRPCTransportServer) {
	// If the following call pancis, it indicates UnimplementedPaladinGRPCTransportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaladinGRPCTransport_ServiceDesc, srv)
}

func _PaladinGRPCTransport_ConnectSendStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PaladinGRPCTransportServer).ConnectSendStream(&grpc.GenericServerStream[Message, Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PaladinGRPCTransport_ConnectSendStreamServer = grpc.ClientStreamingServer[Message, Empty]

// PaladinGRPCTransport_ServiceDesc is the grpc.ServiceDesc for PaladinGRPCTransport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaladinGRPCTransport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.kaleido_io.paladin.transports.grpc.PaladinGRPCTransport",
	HandlerType: (*PaladinGRPCTransportServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConnectSendStream",
			Handler:       _PaladinGRPCTransport_ConnectSendStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/proto/paladin.proto",
}
