export const constants = {
  EVENT_QUERY_LIMIT: 100,
  PENDING_TRANSACTIONS_QUERY_LIMIT: 100,
  REGISTRY_ENTRIES_QUERY_LIMIT: 100,
  TRANSACTION_QUERY_LIMIT: 100,
  UPDATE_FREQUENCY_MILLISECONDS: 3000,
};
