export const constants = {
  COLOR_MODE_STORAGE_KEY: 'color-mode',
  EVENT_QUERY_LIMIT: 10,
  SUBMISSIONS_QUERY_LIMIT: 10,
  REGISTRY_ENTRIES_QUERY_LIMIT: 100,
  TRANSACTION_QUERY_LIMIT: 10,
  UPDATE_FREQUENCY_MILLISECONDS: 3000,
  ELLAPSED_TIME_AUTO_REFRESH_FREQUENCY_SECONDS: 60
};
