contracts:
  factory:
    abiAndBytecode:
      path: ./helpers/abis/ZetoFactory.json
  # the Zeto factory is a CloneFactory, which needs implementation
  # contracts to be set
  implementations:
    # for the deposit transaction
    - name: Groth16Verifier_Deposit
      abiAndBytecode:
        path: ./helpers/abis/Groth16Verifier_Deposit.json
    # for the withdraw transaction
    - name: Groth16Verifier_Withdraw
      abiAndBytecode:
        path: ./helpers/abis/Groth16Verifier_Withdraw.json
    # for the withdraw transaction with batch inputs
    - name: Groth16Verifier_WithdrawBatch
      abiAndBytecode:
        path: ./helpers/abis/Groth16Verifier_WithdrawBatch.json
    # for the Zeto_Anon token
    - name: Groth16Verifier_Anon
      abiAndBytecode:
        path: ./helpers/abis/Groth16Verifier_Anon.json
    - name: Groth16Verifier_AnonBatch
      abiAndBytecode:
        path: ./helpers/abis/Groth16Verifier_AnonBatch.json
    - name: Groth16Verifier_Burn
      abiAndBytecode:
        path: ./helpers/abis/Groth16Verifier_Burn.json
    - name: Groth16Verifier_BurnBatch
      abiAndBytecode:
        path: ./helpers/abis/Groth16Verifier_BurnBatch.json
    - name: Zeto_Anon
      verifier: Groth16Verifier_Anon
      batchVerifier: Groth16Verifier_AnonBatch
      depositVerifier: Groth16Verifier_Deposit
      withdrawVerifier: Groth16Verifier_Withdraw
      batchWithdrawVerifier: Groth16Verifier_WithdrawBatch
      circuits:
        deposit:
          name: deposit
          fungible: true
        withdraw:
          name: withdraw
          fungible: true
        transfer:
          name: anon
          fungible: true
        transferLocked:
          name: anon
          fungible: true
      cloneable: true
      abiAndBytecode:
        path: ./helpers/abis/Zeto_Anon.json
    # for the Zeto_AnonEnc token
    - name: Groth16Verifier_AnonEnc
      abiAndBytecode:
        path: ./helpers/abis/Groth16Verifier_AnonEnc.json
    - name: Groth16Verifier_AnonEncBatch
      abiAndBytecode:
        path: ./helpers/abis/Groth16Verifier_AnonEncBatch.json
    - name: Zeto_AnonEnc
      verifier: Groth16Verifier_AnonEnc
      batchVerifier: Groth16Verifier_AnonEncBatch
      depositVerifier: Groth16Verifier_Deposit
      withdrawVerifier: Groth16Verifier_Withdraw
      batchWithdrawVerifier: Groth16Verifier_WithdrawBatch
      circuits:
        deposit:
          name: deposit
          usesEncryption: true
          fungible: true
        withdraw:
          name: withdraw
          usesEncryption: true
          fungible: true
        transfer:
          name: anon_enc
          usesEncryption: true
          fungible: true
        transferLocked:
          name: anon_enc
          usesEncryption: true
          fungible: true
      cloneable: true
      abiAndBytecode:
        path: ./helpers/abis/Zeto_AnonEnc.json
    # for the Zeto_AnonNullifier token
    - name: PoseidonUnit2L
      abiAndBytecode:
        path: ./helpers/abis/Poseidon2.json
    - name: PoseidonUnit3L
      abiAndBytecode:
        path: ./helpers/abis/Poseidon3.json
    - name: SmtLib
      abiAndBytecode:
        path: ./helpers/abis/SmtLib.json
    - name: Groth16Verifier_WithdrawNullifier
      abiAndBytecode:
        path: ./helpers/abis/Groth16Verifier_WithdrawNullifier.json
    - name: Groth16Verifier_WithdrawNullifierBatch
      abiAndBytecode:
        path: ./helpers/abis/Groth16Verifier_WithdrawNullifierBatch.json
    - name: Groth16Verifier_AnonNullifierTransfer
      abiAndBytecode:
        path: ./helpers/abis/Groth16Verifier_AnonNullifierTransfer.json
    - name: Groth16Verifier_AnonNullifierTransferBatch
      abiAndBytecode:
        path: ./helpers/abis/Groth16Verifier_AnonNullifierTransferBatch.json
    - name: Groth16Verifier_AnonNullifierTransferLocked
      abiAndBytecode:
        path: ./helpers/abis/Groth16Verifier_AnonNullifierTransferLocked.json
    - name: Groth16Verifier_AnonNullifierTransferLockedBatch
      abiAndBytecode:
        path: ./helpers/abis/Groth16Verifier_AnonNullifierTransferLockedBatch.json
    - name: Zeto_AnonNullifier
      verifier: Groth16Verifier_AnonNullifierTransfer
      batchVerifier: Groth16Verifier_AnonNullifierTransferBatch
      depositVerifier: Groth16Verifier_Deposit
      withdrawVerifier: Groth16Verifier_WithdrawNullifier
      batchWithdrawVerifier: Groth16Verifier_WithdrawNullifierBatch
      lockVerifier: Groth16Verifier_AnonNullifierTransferLocked
      batchLockVerifier: Groth16Verifier_AnonNullifierTransferLockedBatch
      circuits:
        deposit:
          name: deposit
        withdraw:
          name: withdraw_nullifier
          usesNullifiers: true
          fungible: true
        transfer:
          name: anon_nullifier_transfer
          usesNullifiers: true
          fungible: true
        transferLocked:
          name: anon_nullifier_transferLocked
          usesNullifiers: true
          fungible: true
      cloneable: true
      abiAndBytecode:
        path: ./helpers/abis/Zeto_AnonNullifier.json
    # for the Zeto_AnonNullifierKyc token
    - name: Groth16Verifier_AnonNullifierKycTransfer
      abiAndBytecode:
        path: ./helpers/abis/Groth16Verifier_AnonNullifierKycTransfer.json
    - name: Groth16Verifier_AnonNullifierKycTransferBatch
      abiAndBytecode:
        path: ./helpers/abis/Groth16Verifier_AnonNullifierKycTransferBatch.json
    - name: Groth16Verifier_AnonNullifierKycTransferLocked
      abiAndBytecode:
        path: ./helpers/abis/Groth16Verifier_AnonNullifierKycTransferLocked.json
    - name: Groth16Verifier_AnonNullifierKycTransferLockedBatch
      abiAndBytecode:
        path: ./helpers/abis/Groth16Verifier_AnonNullifierKycTransferLockedBatch.json
    - name: Zeto_AnonNullifierKyc
      verifier: Groth16Verifier_AnonNullifierKycTransfer
      batchVerifier: Groth16Verifier_AnonNullifierKycTransferBatch
      depositVerifier: Groth16Verifier_Deposit
      withdrawVerifier: Groth16Verifier_WithdrawNullifier
      batchWithdrawVerifier: Groth16Verifier_WithdrawNullifierBatch
      lockVerifier: Groth16Verifier_AnonNullifierKycTransferLocked
      batchLockVerifier: Groth16Verifier_AnonNullifierKycTransferLockedBatch
      circuits:
        deposit:
          name: deposit
        withdraw:
          name: withdraw_nullifier
          usesNullifiers: true
          fungible: true
        transfer:
          name: anon_nullifier_kyc_transfer
          usesNullifiers: true
          usesKyc: true
          fungible: true
        transferLocked:
          name: anon_nullifier_kyc_transferLocked
          usesNullifiers: true
          usesKyc: true
          fungible: true
      cloneable: true
      abiAndBytecode:
        path: ./helpers/abis/Zeto_AnonNullifierKyc.json
