// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package transaction

import (
	"context"
	"time"

	"github.com/LFDT-Paladin/paladin/core/internal/components"
	"github.com/LFDT-Paladin/paladin/core/internal/sequencer/common"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEvent creates a new instance of MockEvent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEvent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEvent {
	mock := &MockEvent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEvent is an autogenerated mock type for the Event type
type MockEvent struct {
	mock.Mock
}

type MockEvent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEvent) EXPECT() *MockEvent_Expecter {
	return &MockEvent_Expecter{mock: &_m.Mock}
}

// GetEventTime provides a mock function for the type MockEvent
func (_mock *MockEvent) GetEventTime() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEventTime")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockEvent_GetEventTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventTime'
type MockEvent_GetEventTime_Call struct {
	*mock.Call
}

// GetEventTime is a helper method to define mock.On call
func (_e *MockEvent_Expecter) GetEventTime() *MockEvent_GetEventTime_Call {
	return &MockEvent_GetEventTime_Call{Call: _e.mock.On("GetEventTime")}
}

func (_c *MockEvent_GetEventTime_Call) Run(run func()) *MockEvent_GetEventTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvent_GetEventTime_Call) Return(time1 time.Time) *MockEvent_GetEventTime_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockEvent_GetEventTime_Call) RunAndReturn(run func() time.Time) *MockEvent_GetEventTime_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransactionID provides a mock function for the type MockEvent
func (_mock *MockEvent) GetTransactionID() uuid.UUID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionID")
	}

	var r0 uuid.UUID
	if returnFunc, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	return r0
}

// MockEvent_GetTransactionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactionID'
type MockEvent_GetTransactionID_Call struct {
	*mock.Call
}

// GetTransactionID is a helper method to define mock.On call
func (_e *MockEvent_Expecter) GetTransactionID() *MockEvent_GetTransactionID_Call {
	return &MockEvent_GetTransactionID_Call{Call: _e.mock.On("GetTransactionID")}
}

func (_c *MockEvent_GetTransactionID_Call) Run(run func()) *MockEvent_GetTransactionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvent_GetTransactionID_Call) Return(uUID uuid.UUID) *MockEvent_GetTransactionID_Call {
	_c.Call.Return(uUID)
	return _c
}

func (_c *MockEvent_GetTransactionID_Call) RunAndReturn(run func() uuid.UUID) *MockEvent_GetTransactionID_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function for the type MockEvent
func (_mock *MockEvent) Type() common.EventType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 common.EventType
	if returnFunc, ok := ret.Get(0).(func() common.EventType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(common.EventType)
	}
	return r0
}

// MockEvent_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockEvent_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockEvent_Expecter) Type() *MockEvent_Type_Call {
	return &MockEvent_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockEvent_Type_Call) Run(run func()) *MockEvent_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvent_Type_Call) Return(eventType common.EventType) *MockEvent_Type_Call {
	_c.Call.Return(eventType)
	return _c
}

func (_c *MockEvent_Type_Call) RunAndReturn(run func() common.EventType) *MockEvent_Type_Call {
	_c.Call.Return(run)
	return _c
}

// TypeString provides a mock function for the type MockEvent
func (_mock *MockEvent) TypeString() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TypeString")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockEvent_TypeString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TypeString'
type MockEvent_TypeString_Call struct {
	*mock.Call
}

// TypeString is a helper method to define mock.On call
func (_e *MockEvent_Expecter) TypeString() *MockEvent_TypeString_Call {
	return &MockEvent_TypeString_Call{Call: _e.mock.On("TypeString")}
}

func (_c *MockEvent_TypeString_Call) Run(run func()) *MockEvent_TypeString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvent_TypeString_Call) Return(s string) *MockEvent_TypeString_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockEvent_TypeString_Call) RunAndReturn(run func() string) *MockEvent_TypeString_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOriginatorTransaction creates a new instance of MockOriginatorTransaction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOriginatorTransaction(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOriginatorTransaction {
	mock := &MockOriginatorTransaction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOriginatorTransaction is an autogenerated mock type for the OriginatorTransaction type
type MockOriginatorTransaction struct {
	mock.Mock
}

type MockOriginatorTransaction_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOriginatorTransaction) EXPECT() *MockOriginatorTransaction_Expecter {
	return &MockOriginatorTransaction_Expecter{mock: &_m.Mock}
}

// GetCurrentState provides a mock function for the type MockOriginatorTransaction
func (_mock *MockOriginatorTransaction) GetCurrentState() State {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentState")
	}

	var r0 State
	if returnFunc, ok := ret.Get(0).(func() State); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(State)
	}
	return r0
}

// MockOriginatorTransaction_GetCurrentState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentState'
type MockOriginatorTransaction_GetCurrentState_Call struct {
	*mock.Call
}

// GetCurrentState is a helper method to define mock.On call
func (_e *MockOriginatorTransaction_Expecter) GetCurrentState() *MockOriginatorTransaction_GetCurrentState_Call {
	return &MockOriginatorTransaction_GetCurrentState_Call{Call: _e.mock.On("GetCurrentState")}
}

func (_c *MockOriginatorTransaction_GetCurrentState_Call) Run(run func()) *MockOriginatorTransaction_GetCurrentState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOriginatorTransaction_GetCurrentState_Call) Return(state State) *MockOriginatorTransaction_GetCurrentState_Call {
	_c.Call.Return(state)
	return _c
}

func (_c *MockOriginatorTransaction_GetCurrentState_Call) RunAndReturn(run func() State) *MockOriginatorTransaction_GetCurrentState_Call {
	_c.Call.Return(run)
	return _c
}

// GetID provides a mock function for the type MockOriginatorTransaction
func (_mock *MockOriginatorTransaction) GetID() uuid.UUID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 uuid.UUID
	if returnFunc, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	return r0
}

// MockOriginatorTransaction_GetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetID'
type MockOriginatorTransaction_GetID_Call struct {
	*mock.Call
}

// GetID is a helper method to define mock.On call
func (_e *MockOriginatorTransaction_Expecter) GetID() *MockOriginatorTransaction_GetID_Call {
	return &MockOriginatorTransaction_GetID_Call{Call: _e.mock.On("GetID")}
}

func (_c *MockOriginatorTransaction_GetID_Call) Run(run func()) *MockOriginatorTransaction_GetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOriginatorTransaction_GetID_Call) Return(uUID uuid.UUID) *MockOriginatorTransaction_GetID_Call {
	_c.Call.Return(uUID)
	return _c
}

func (_c *MockOriginatorTransaction_GetID_Call) RunAndReturn(run func() uuid.UUID) *MockOriginatorTransaction_GetID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrivateTransaction provides a mock function for the type MockOriginatorTransaction
func (_mock *MockOriginatorTransaction) GetPrivateTransaction() *components.PrivateTransaction {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPrivateTransaction")
	}

	var r0 *components.PrivateTransaction
	if returnFunc, ok := ret.Get(0).(func() *components.PrivateTransaction); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*components.PrivateTransaction)
		}
	}
	return r0
}

// MockOriginatorTransaction_GetPrivateTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrivateTransaction'
type MockOriginatorTransaction_GetPrivateTransaction_Call struct {
	*mock.Call
}

// GetPrivateTransaction is a helper method to define mock.On call
func (_e *MockOriginatorTransaction_Expecter) GetPrivateTransaction() *MockOriginatorTransaction_GetPrivateTransaction_Call {
	return &MockOriginatorTransaction_GetPrivateTransaction_Call{Call: _e.mock.On("GetPrivateTransaction")}
}

func (_c *MockOriginatorTransaction_GetPrivateTransaction_Call) Run(run func()) *MockOriginatorTransaction_GetPrivateTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOriginatorTransaction_GetPrivateTransaction_Call) Return(privateTransaction *components.PrivateTransaction) *MockOriginatorTransaction_GetPrivateTransaction_Call {
	_c.Call.Return(privateTransaction)
	return _c
}

func (_c *MockOriginatorTransaction_GetPrivateTransaction_Call) RunAndReturn(run func() *components.PrivateTransaction) *MockOriginatorTransaction_GetPrivateTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function for the type MockOriginatorTransaction
func (_mock *MockOriginatorTransaction) GetStatus(ctx context.Context) components.PrivateTxStatus {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 components.PrivateTxStatus
	if returnFunc, ok := ret.Get(0).(func(context.Context) components.PrivateTxStatus); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(components.PrivateTxStatus)
	}
	return r0
}

// MockOriginatorTransaction_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type MockOriginatorTransaction_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOriginatorTransaction_Expecter) GetStatus(ctx interface{}) *MockOriginatorTransaction_GetStatus_Call {
	return &MockOriginatorTransaction_GetStatus_Call{Call: _e.mock.On("GetStatus", ctx)}
}

func (_c *MockOriginatorTransaction_GetStatus_Call) Run(run func(ctx context.Context)) *MockOriginatorTransaction_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOriginatorTransaction_GetStatus_Call) Return(privateTxStatus components.PrivateTxStatus) *MockOriginatorTransaction_GetStatus_Call {
	_c.Call.Return(privateTxStatus)
	return _c
}

func (_c *MockOriginatorTransaction_GetStatus_Call) RunAndReturn(run func(ctx context.Context) components.PrivateTxStatus) *MockOriginatorTransaction_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// HandleEvent provides a mock function for the type MockOriginatorTransaction
func (_mock *MockOriginatorTransaction) HandleEvent(ctx context.Context, event common.Event) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for HandleEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Event) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOriginatorTransaction_HandleEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleEvent'
type MockOriginatorTransaction_HandleEvent_Call struct {
	*mock.Call
}

// HandleEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event common.Event
func (_e *MockOriginatorTransaction_Expecter) HandleEvent(ctx interface{}, event interface{}) *MockOriginatorTransaction_HandleEvent_Call {
	return &MockOriginatorTransaction_HandleEvent_Call{Call: _e.mock.On("HandleEvent", ctx, event)}
}

func (_c *MockOriginatorTransaction_HandleEvent_Call) Run(run func(ctx context.Context, event common.Event)) *MockOriginatorTransaction_HandleEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 common.Event
		if args[1] != nil {
			arg1 = args[1].(common.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOriginatorTransaction_HandleEvent_Call) Return(err error) *MockOriginatorTransaction_HandleEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOriginatorTransaction_HandleEvent_Call) RunAndReturn(run func(ctx context.Context, event common.Event) error) *MockOriginatorTransaction_HandleEvent_Call {
	_c.Call.Return(run)
	return _c
}
