// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.20;

/**
 * @title ILockableCapability
 * @dev Generic interface for representing a locked capability that can be
 *      delegated and eventually consumed ("spent") or cancelled by a
 *      designated spender.
 *
 *      A "capability" here is any predefined state-changing operation: it may
 *      involve tokens, a function call, or any other effect defined by the
 *      implementing contract.
 *
 *      Core guarantees:
 *        - Each lock is identified by a unique lockId, generated by the
 *          implementing contract.
 *        - For each active lock, there is exactly one current spender
 *          address (the "authorized spender").
 *        - Initially, the lock creator is both the owner and the spender.
 *        - Only the current spender is allowed to spend, cancel, or delegate
 *          the lock.
 *        - This interface does not prescribe expiry, auto-cancellation, or
 *          owner-controlled clawback. Once a lock is created and delegated,
 *          the original owner cannot prevent the current spender from using
 *          it (except by becoming the current spender again through delegation).
 *        - Constraints beyond this base model should be implemented by delegating
 *          the lock to a separate policy contract.
 *
 *      The intent is that, so long as a lock remains active and the caller is
 *      the current spender, the implementing contract MUST NOT introduce
 *      arbitrary revocation or expiry logic beyond:
 *        - the lock having already been spent or cancelled; or
 *        - the caller not being the current spender; or
 *        - the provided data failing validation as defined by the specific
 *          implementation.
 *
 *      Notes on dynamically typed arguments:
 *        - Each `*Args` parameter contains implementation-specific,
 *          ABI-encoded calldata used to carry out that lifecycle action.
 *          Implementations are RECOMMENDED to define and document a canonical
 *          struct type for each such argument payload, and to encode that
 *          struct using `abi.encode(...)` when calling the interface methods.
 *        - Each `data` parameter contains application-specific calldata,
 *          which is passed through to emitted events.
 */
interface ILockableCapability {
    /**
     * @dev Stored lock info available to query by lockId.
     */
    struct LockInfo {
        /**
         * @dev The address that originally created the lock.
         *      Immutable for the lifetime of the lock.
         */
        address owner;

        /**
         * @dev The address currently authorized to spend, cancel, or delegate the lock.
         *      Mutable by the current spender while the lock remains active.
         */
        address spender;

        /**
         * @dev An implementation-defined commitment to the spend operation permitted for this lock.
         *      Zero if unrestricted.
         *      Mutable if and only if the lock is active and owner-controlled
         *      (`spender == owner`).
         */
        bytes32 spendCommitment;

        /**
         * @dev An implementation-defined commitment to the cancellation operation permitted for this lock.
         *      Zero if unrestricted.
         *      Mutable if and only if the lock is active and owner-controlled
         *      (`spender == owner`).
         */
        bytes32 cancelCommitment;
    }

    /**
     * @dev Emitted when a lock is created.
     */
    event LockCreated(
        bytes32 indexed lockId,
        address indexed owner,
        address indexed spender,
        bytes32 spendCommitment,
        bytes32 cancelCommitment,
        bytes data
    );

    /**
     * @dev Emitted when an active lock is updated.
     */
    event LockUpdated(
        bytes32 indexed lockId,
        address indexed owner,
        bytes32 spendCommitment,
        bytes32 cancelCommitment,
        bytes data
    );

    /**
     * @dev Emitted when spending authority is delegated from one address to another.
     */
    event LockDelegated(
        bytes32 indexed lockId,
        address indexed from,
        address indexed to,
        bytes data
    );

    /**
     * @dev Emitted when a lock is successfully spent.
     */
    event LockSpent(
        bytes32 indexed lockId,
        address indexed spender,
        bytes data
    );

    /**
     * @dev Emitted when a lock is successfully cancelled.
     */
    event LockCancelled(
        bytes32 indexed lockId,
        address indexed spender,
        bytes data
    );

    /**
     * @dev Thrown when a lock does not exist or is not active.
     */
    error LockNotActive(bytes32 lockId);

    /**
     * @dev Thrown when the caller is not the current spender for the given lock.
     */
    error LockUnauthorized(bytes32 lockId, address spender, address caller);

    /**
     * @dev Thrown when an attempted mutation is not permitted under the lock's
     *      mutability rules.
     */
    error LockImmutable(bytes32 lockId);

    /**
     * @dev Create a new lock.
     *      Moves control of the relevant value/state/activity to the lock.
     *
     *      Locks are identified by a unique lockId, generated in an
     *      implementation-specific way.
     *      Implementations SHOULD generate lockId deterministically from
     *      immutable lock properties where practical.
     *
     * Requirements:
     *  - MUST create the lock in the active state
     *  - MUST set owner to msg.sender
     *  - MUST set spender to msg.sender initially
     *
     * @param createArgs       Implementation-specific calldata needed to create the lock.
     * @param spendCommitment  An implementation-defined commitment to the spend operation permitted for this lock.
     * @param cancelCommitment An implementation-defined commitment to the cancellation operation permitted for this lock.
     * @param data             Auxiliary application-specific calldata.
     * @return lockId          The generated unique identifier for the lock.
     *
     * Emits a {LockCreated} event.
     */
    function createLock(
        bytes calldata createArgs,
        bytes32 spendCommitment,
        bytes32 cancelCommitment,
        bytes calldata data
    ) external returns (bytes32 lockId);

    /**
     * @dev Update an existing active, owner-controlled lock.
     *
     *      `spendCommitment` and `cancelCommitment` fully replace the previous
     *      commitment values.
     *      Delegates can never alter the shape or purpose of a lock.
     *
     * Requirements:
     *  - MUST revert with LockNotActive(lockId) if the lock is not active
     *  - MUST revert with LockImmutable(lockId) unless the lock is currently
     *    owner-controlled (`spender == owner`) and the requested mutation is
     *    permitted by the implementation
     *
     * @param lockId           The unique identifier for the lock.
     * @param updateArgs       Implementation-specific calldata needed to update the lock.
     * @param spendCommitment  Replacement spend commitment.
     * @param cancelCommitment Replacement cancel commitment.
     * @param data             Auxiliary application-specific calldata.
     *
     * Emits a {LockUpdated} event.
     */
    function updateLock(
        bytes32 lockId,
        bytes calldata updateArgs,
        bytes32 spendCommitment,
        bytes32 cancelCommitment,
        bytes calldata data
    ) external;

    /**
     * @dev Delegate spending authority for this lock to a new address.
     *
     *      After delegation:
     *        - The previous spender MUST no longer be allowed to spend or
     *          cancel the lock (unless they later regain spender status).
     *        - `spendCommitment` and `cancelCommitment` MUST be immutable while
     *          the lock is not owner-controlled.
     *
     *      Delegation is reversible by the current spender, including
     *      delegation back to the owner.
     *
     * Requirements:
     *  - MUST revert with LockUnauthorized(lockId, currentSpender, msg.sender)
     *    if msg.sender is not the current spender for lockId
     *  - MUST revert with LockNotActive(lockId) if the lock is not active
     *
     * @param lockId       The unique identifier for the lock.
     * @param delegateArgs Implementation-specific calldata needed to delegate the lock.
     * @param newSpender   The address to delegate the lock to.
     * @param data         Auxiliary application-specific calldata.
     *
     * Emits a {LockDelegated} event.
     */
    function delegateLock(
        bytes32 lockId,
        bytes calldata delegateArgs,
        address newSpender,
        bytes calldata data
    ) external;

    /**
     * @dev Spend the lock.
     *      Consumes or executes the effect of the lock (for example: releasing tokens,
     *      executing a function call, etc).
     *
     * Requirements:
     *  - MUST revert with LockUnauthorized(lockId, currentSpender, msg.sender)
     *    if msg.sender is not the current spender for lockId
     *  - MUST revert with LockNotActive(lockId) if the lock is not active
     *  - MUST remove the lock (or mark as inactive) if successful
     *
     * @param lockId    The unique identifier for the lock.
     * @param spendArgs Implementation-specific calldata needed to spend the lock.
     * @param data      Auxiliary application-specific calldata.
     *
     * Emits a {LockSpent} event.
     */
    function spendLock(
        bytes32 lockId,
        bytes calldata spendArgs,
        bytes calldata data
    ) external;

    /**
     * @dev Cancel the lock.
     *      Performs the cancellation operation for the lock (for example: refunding
     *      tokens, executing a function call, etc).
     *
     * Requirements:
     *  - MUST revert with LockUnauthorized(lockId, currentSpender, msg.sender)
     *    if msg.sender is not the current spender for lockId
     *  - MUST revert with LockNotActive(lockId) if the lock is not active
     *  - MUST remove the lock (or mark as inactive) if successful
     *
     * @param lockId     The unique identifier for the lock.
     * @param cancelArgs Implementation-specific calldata needed to cancel the lock.
     * @param data       Auxiliary application-specific calldata.
     *
     * Emits a {LockCancelled} event.
     */
    function cancelLock(
        bytes32 lockId,
        bytes calldata cancelArgs,
        bytes calldata data
    ) external;

    /**
     * @dev Get stored lock information for an active lock.
     *
     * Requirements:
     *  - MUST revert with LockNotActive(lockId) if the lock is not active.
     *
     * @param lockId The unique identifier for the lock.
     * @return info  Stored lock information.
     */
    function getLock(
        bytes32 lockId
    ) external view returns (LockInfo memory info);

    /**
     * @dev Query whether the lock is currently active.
     *
     *      MUST return false for locks that do not exist and for locks that
     *      have been spent or cancelled.
     *
     * @param lockId The unique identifier for the lock.
     * @return active Whether the lock is currently active.
     */
    function isLockActive(bytes32 lockId) external view returns (bool active);

    /**
     * @dev Get implementation-specific lock content for an active lock.
     *
     *      This represents the data or operation that was locked, and is
     *      immutable once the lock is created.
     *
     * Requirements:
     *  - MUST revert with LockNotActive(lockId) if the lock is not active.
     *
     * @param lockId The unique identifier for the lock.
     * @return content The implementation-specific lock content.
     */
    function getLockContent(
        bytes32 lockId
    ) external view returns (bytes memory content);
}
