// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package coordinator

import (
	"context"
	"time"

	"github.com/LFDT-Paladin/paladin/core/internal/sequencer/common"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCoordinator creates a new instance of MockCoordinator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCoordinator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCoordinator {
	mock := &MockCoordinator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCoordinator is an autogenerated mock type for the Coordinator type
type MockCoordinator struct {
	mock.Mock
}

type MockCoordinator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCoordinator) EXPECT() *MockCoordinator_Expecter {
	return &MockCoordinator_Expecter{mock: &_m.Mock}
}

// GetCurrentState provides a mock function for the type MockCoordinator
func (_mock *MockCoordinator) GetCurrentState() State {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentState")
	}

	var r0 State
	if returnFunc, ok := ret.Get(0).(func() State); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(State)
	}
	return r0
}

// MockCoordinator_GetCurrentState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentState'
type MockCoordinator_GetCurrentState_Call struct {
	*mock.Call
}

// GetCurrentState is a helper method to define mock.On call
func (_e *MockCoordinator_Expecter) GetCurrentState() *MockCoordinator_GetCurrentState_Call {
	return &MockCoordinator_GetCurrentState_Call{Call: _e.mock.On("GetCurrentState")}
}

func (_c *MockCoordinator_GetCurrentState_Call) Run(run func()) *MockCoordinator_GetCurrentState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCoordinator_GetCurrentState_Call) Return(state State) *MockCoordinator_GetCurrentState_Call {
	_c.Call.Return(state)
	return _c
}

func (_c *MockCoordinator_GetCurrentState_Call) RunAndReturn(run func() State) *MockCoordinator_GetCurrentState_Call {
	_c.Call.Return(run)
	return _c
}

// QueueEvent provides a mock function for the type MockCoordinator
func (_mock *MockCoordinator) QueueEvent(ctx context.Context, event common.Event) {
	_mock.Called(ctx, event)
	return
}

// MockCoordinator_QueueEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueueEvent'
type MockCoordinator_QueueEvent_Call struct {
	*mock.Call
}

// QueueEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event common.Event
func (_e *MockCoordinator_Expecter) QueueEvent(ctx interface{}, event interface{}) *MockCoordinator_QueueEvent_Call {
	return &MockCoordinator_QueueEvent_Call{Call: _e.mock.On("QueueEvent", ctx, event)}
}

func (_c *MockCoordinator_QueueEvent_Call) Run(run func(ctx context.Context, event common.Event)) *MockCoordinator_QueueEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 common.Event
		if args[1] != nil {
			arg1 = args[1].(common.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCoordinator_QueueEvent_Call) Return() *MockCoordinator_QueueEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCoordinator_QueueEvent_Call) RunAndReturn(run func(ctx context.Context, event common.Event)) *MockCoordinator_QueueEvent_Call {
	_c.Run(run)
	return _c
}

// TryQueueEvent provides a mock function for the type MockCoordinator
func (_mock *MockCoordinator) TryQueueEvent(ctx context.Context, event common.Event) bool {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for TryQueueEvent")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.Event) bool); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockCoordinator_TryQueueEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TryQueueEvent'
type MockCoordinator_TryQueueEvent_Call struct {
	*mock.Call
}

// TryQueueEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event common.Event
func (_e *MockCoordinator_Expecter) TryQueueEvent(ctx interface{}, event interface{}) *MockCoordinator_TryQueueEvent_Call {
	return &MockCoordinator_TryQueueEvent_Call{Call: _e.mock.On("TryQueueEvent", ctx, event)}
}

func (_c *MockCoordinator_TryQueueEvent_Call) Run(run func(ctx context.Context, event common.Event)) *MockCoordinator_TryQueueEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 common.Event
		if args[1] != nil {
			arg1 = args[1].(common.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCoordinator_TryQueueEvent_Call) Return(b bool) *MockCoordinator_TryQueueEvent_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockCoordinator_TryQueueEvent_Call) RunAndReturn(run func(ctx context.Context, event common.Event) bool) *MockCoordinator_TryQueueEvent_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForDone provides a mock function for the type MockCoordinator
func (_mock *MockCoordinator) WaitForDone(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockCoordinator_WaitForDone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForDone'
type MockCoordinator_WaitForDone_Call struct {
	*mock.Call
}

// WaitForDone is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCoordinator_Expecter) WaitForDone(ctx interface{}) *MockCoordinator_WaitForDone_Call {
	return &MockCoordinator_WaitForDone_Call{Call: _e.mock.On("WaitForDone", ctx)}
}

func (_c *MockCoordinator_WaitForDone_Call) Run(run func(ctx context.Context)) *MockCoordinator_WaitForDone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCoordinator_WaitForDone_Call) Return() *MockCoordinator_WaitForDone_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCoordinator_WaitForDone_Call) RunAndReturn(run func(ctx context.Context)) *MockCoordinator_WaitForDone_Call {
	_c.Run(run)
	return _c
}

// NewMockEvent creates a new instance of MockEvent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEvent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEvent {
	mock := &MockEvent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEvent is an autogenerated mock type for the Event type
type MockEvent struct {
	mock.Mock
}

type MockEvent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEvent) EXPECT() *MockEvent_Expecter {
	return &MockEvent_Expecter{mock: &_m.Mock}
}

// GetEventTime provides a mock function for the type MockEvent
func (_mock *MockEvent) GetEventTime() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEventTime")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockEvent_GetEventTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventTime'
type MockEvent_GetEventTime_Call struct {
	*mock.Call
}

// GetEventTime is a helper method to define mock.On call
func (_e *MockEvent_Expecter) GetEventTime() *MockEvent_GetEventTime_Call {
	return &MockEvent_GetEventTime_Call{Call: _e.mock.On("GetEventTime")}
}

func (_c *MockEvent_GetEventTime_Call) Run(run func()) *MockEvent_GetEventTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvent_GetEventTime_Call) Return(time1 time.Time) *MockEvent_GetEventTime_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockEvent_GetEventTime_Call) RunAndReturn(run func() time.Time) *MockEvent_GetEventTime_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function for the type MockEvent
func (_mock *MockEvent) Type() common.EventType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 common.EventType
	if returnFunc, ok := ret.Get(0).(func() common.EventType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(common.EventType)
	}
	return r0
}

// MockEvent_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockEvent_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockEvent_Expecter) Type() *MockEvent_Type_Call {
	return &MockEvent_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockEvent_Type_Call) Run(run func()) *MockEvent_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvent_Type_Call) Return(eventType common.EventType) *MockEvent_Type_Call {
	_c.Call.Return(eventType)
	return _c
}

func (_c *MockEvent_Type_Call) RunAndReturn(run func() common.EventType) *MockEvent_Type_Call {
	_c.Call.Return(run)
	return _c
}

// TypeString provides a mock function for the type MockEvent
func (_mock *MockEvent) TypeString() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TypeString")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockEvent_TypeString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TypeString'
type MockEvent_TypeString_Call struct {
	*mock.Call
}

// TypeString is a helper method to define mock.On call
func (_e *MockEvent_Expecter) TypeString() *MockEvent_TypeString_Call {
	return &MockEvent_TypeString_Call{Call: _e.mock.On("TypeString")}
}

func (_c *MockEvent_TypeString_Call) Run(run func()) *MockEvent_TypeString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvent_TypeString_Call) Return(s string) *MockEvent_TypeString_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockEvent_TypeString_Call) RunAndReturn(run func() string) *MockEvent_TypeString_Call {
	_c.Call.Return(run)
	return _c
}
