apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.operator.name }}
rules:
- apiGroups:
  - core.paladin.io
  resources:
  - smartcontractdeployments
  - transactioninvokes
  - besus
  - paladins
  - besugeneses
  - paladinregistries
  - paladindomains
  - paladinregistrations 
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.paladin.io
  resources:
  - smartcontractdeployments/status
  - transactioninvokes/status
  - besus/status
  - paladins/status
  - besugeneses/status
  - paladinregistries/status
  - paladindomains/status
  - paladinregistrations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - get
  - list
  - create
  - delete
  - update
  - patch
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - create
  - delete
  - update
  - patch
  - watch
- apiGroups:
  - ""  # core
  resources:
  - services
  - configmaps
  - secrets
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - create
  - delete
  - update
  - patch
  - watch
- apiGroups:
  - "policy"
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - create
  - delete
  - update
  - patch
  - watch
