// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.1
// source: inter-paladin-transport.proto

package InterPaladinTransport

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InterPaladinMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *InterPaladinMessage) Reset() {
	*x = InterPaladinMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inter_paladin_transport_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterPaladinMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterPaladinMessage) ProtoMessage() {}

func (x *InterPaladinMessage) ProtoReflect() protoreflect.Message {
	mi := &file_inter_paladin_transport_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterPaladinMessage.ProtoReflect.Descriptor instead.
func (*InterPaladinMessage) Descriptor() ([]byte, []int) {
	return file_inter_paladin_transport_proto_rawDescGZIP(), []int{0}
}

func (x *InterPaladinMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type InterPaladinReceipt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *InterPaladinReceipt) Reset() {
	*x = InterPaladinReceipt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inter_paladin_transport_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterPaladinReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterPaladinReceipt) ProtoMessage() {}

func (x *InterPaladinReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_inter_paladin_transport_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterPaladinReceipt.ProtoReflect.Descriptor instead.
func (*InterPaladinReceipt) Descriptor() ([]byte, []int) {
	return file_inter_paladin_transport_proto_rawDescGZIP(), []int{1}
}

func (x *InterPaladinReceipt) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_inter_paladin_transport_proto protoreflect.FileDescriptor

var file_inter_paladin_transport_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x2d, 0x70, 0x61, 0x6c, 0x61, 0x64, 0x69, 0x6e, 0x2d,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x61, 0x6c,
	0x61, 0x64, 0x69, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x2f, 0x0a,
	0x13, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x61, 0x6c, 0x61, 0x64, 0x69, 0x6e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x2f,
	0x0a, 0x13, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x61, 0x6c, 0x61, 0x64, 0x69, 0x6e, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x70, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x32,
	0x9b, 0x01, 0x0a, 0x15, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x61, 0x6c, 0x61, 0x64, 0x69, 0x6e,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x81, 0x01, 0x0a, 0x17, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x50, 0x61, 0x6c, 0x61, 0x64, 0x69, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x46, 0x6c, 0x6f, 0x77, 0x12, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x50, 0x61, 0x6c, 0x61, 0x64, 0x69, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x70, 0x6f, 0x72, 0x74, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x61, 0x6c, 0x61, 0x64, 0x69,
	0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x61, 0x6c, 0x61, 0x64, 0x69, 0x6e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x61, 0x6c,
	0x61, 0x64, 0x69, 0x6e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x22, 0x00, 0x42, 0x1e, 0x5a,
	0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x61, 0x6c,
	0x61, 0x64, 0x69, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_inter_paladin_transport_proto_rawDescOnce sync.Once
	file_inter_paladin_transport_proto_rawDescData = file_inter_paladin_transport_proto_rawDesc
)

func file_inter_paladin_transport_proto_rawDescGZIP() []byte {
	file_inter_paladin_transport_proto_rawDescOnce.Do(func() {
		file_inter_paladin_transport_proto_rawDescData = protoimpl.X.CompressGZIP(file_inter_paladin_transport_proto_rawDescData)
	})
	return file_inter_paladin_transport_proto_rawDescData
}

var file_inter_paladin_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_inter_paladin_transport_proto_goTypes = []interface{}{
	(*InterPaladinMessage)(nil), // 0: protos.InterPaladinTransport.InterPaladinMessage
	(*InterPaladinReceipt)(nil), // 1: protos.InterPaladinTransport.InterPaladinReceipt
}
var file_inter_paladin_transport_proto_depIdxs = []int32{
	0, // 0: protos.InterPaladinTransport.InterPaladinTransport.InterPaladinMessageFlow:input_type -> protos.InterPaladinTransport.InterPaladinMessage
	1, // 1: protos.InterPaladinTransport.InterPaladinTransport.InterPaladinMessageFlow:output_type -> protos.InterPaladinTransport.InterPaladinReceipt
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_inter_paladin_transport_proto_init() }
func file_inter_paladin_transport_proto_init() {
	if File_inter_paladin_transport_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_inter_paladin_transport_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InterPaladinMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inter_paladin_transport_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InterPaladinReceipt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inter_paladin_transport_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inter_paladin_transport_proto_goTypes,
		DependencyIndexes: file_inter_paladin_transport_proto_depIdxs,
		MessageInfos:      file_inter_paladin_transport_proto_msgTypes,
	}.Build()
	File_inter_paladin_transport_proto = out.File
	file_inter_paladin_transport_proto_rawDesc = nil
	file_inter_paladin_transport_proto_goTypes = nil
	file_inter_paladin_transport_proto_depIdxs = nil
}
