build-tags: generate_mocks
template: testify
pkgname: "{{.SrcPackageName}}mocks"
structname: "{{.InterfaceName}}"
filename: "{{.SrcPackageName}}mocks.go"
dir: "mocks/{{.SrcPackageName}}mocks"
packages:
  github.com/LFDT-Paladin/paladin/sdk/go/pkg/rpcclient:
    config:
      all: true
  github.com/LFDT-Paladin/paladin/toolkit/pkg/rpcserver:
    config:
      all: true
  github.com/LFDT-Paladin/paladin/toolkit/pkg/signer:
    interfaces:
      SigningModule:
  github.com/LFDT-Paladin/paladin/core/pkg/persistence:
    config:
      all: true
  github.com/LFDT-Paladin/paladin/core/pkg/blockindexer:    
    interfaces:
      BlockIndexer:
      EventStream:
  github.com/LFDT-Paladin/paladin/core/pkg/ethclient:
    config:
      all: true
  github.com/LFDT-Paladin/paladin/core/internal/components:
    config:
      all: true
  github.com/LFDT-Paladin/paladin/core/internal/componentmgr:
    config:
      all: true
  github.com/LFDT-Paladin/paladin/core/internal/metrics:
    config:
      all: true
  github.com/LFDT-Paladin/paladin/core/internal/rpcauthmgr:
    config:
      all: true
  github.com/LFDT-Paladin/paladin/core/internal/publictxmgr:
    interfaces:
      InFlightStageActionTriggers:
  github.com/LFDT-Paladin/paladin/core/internal/sequencer/coordinator:
    config:
      all: true
  github.com/LFDT-Paladin/paladin/core/internal/sequencer/coordinator/grapher:
    config:
      all: true
  github.com/LFDT-Paladin/paladin/core/internal/sequencer/coordinator/statevisibilitytracker:
    config:
      all: true
  github.com/LFDT-Paladin/paladin/core/internal/sequencer/coordinator/transaction:
    config:
      pkgname: coordinatortransactionmocks
      dir: mocks/coordinatortransactionmocks
      all: true    
  github.com/LFDT-Paladin/paladin/core/internal/sequencer/common:
    interfaces:
      EngineIntegration:
      Clock:
    config:
      pkgname: sequencercommonmocks
      dir: mocks/sequencercommonmocks
  github.com/LFDT-Paladin/paladin/core/internal/sequencer/transport:
    config:
      pkgname: sequencertransportmocks
      dir: mocks/sequencertransportmocks
      all: true 
  github.com/LFDT-Paladin/paladin/core/internal/sequencer/syncpoints:
    config:
      all: true
  github.com/LFDT-Paladin/paladin/core/internal/sequencer/metrics:
    config:
      all: true
      pkgname: sequencermetricsmocks
      dir: mocks/sequencermetricsmocks
  github.com/LFDT-Paladin/paladin/core/internal/sequencer/originator/transaction:
    config:
      all: true
      pkgname: originatortransactionmocks
      dir: mocks/originatortransactionmocks
  github.com/LFDT-Paladin/paladin/core/internal/sequencer/originator:
    config:
      all: true
