/*
 * Copyright © 2024 Kaleido, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package noto

import (
	"context"

	"github.com/LFDT-Paladin/paladin/domains/noto/pkg/types"
	"github.com/LFDT-Paladin/paladin/sdk/go/pkg/pldtypes"
	"github.com/LFDT-Paladin/paladin/toolkit/pkg/prototk"
)

type manifestBuilder struct {
	n                 *Noto
	outputs           preparedOutputs
	lockedOutputs     preparedLockedOutputs
	infoStates        []*prototk.NewState
	infoDistributions []identityList
	lockInfo          *preparedLockInfo
	// The Noto manifest currently only includes the new states generated by the transactions (outputs & info).
	// The assertion is that the input states are known already by all parties who require them (sender and notary).
}

func (n *Noto) newManifestBuilder() *manifestBuilder {
	return &manifestBuilder{n: n}
}

func (mb *manifestBuilder) addOutputs(po *preparedOutputs) *manifestBuilder {
	if po == nil {
		return mb
	}
	mb.outputs.distributions = append(mb.outputs.distributions, po.distributions...)
	mb.outputs.coins = append(mb.outputs.coins, po.coins...)
	mb.outputs.states = append(mb.outputs.states, po.states...)
	return mb
}

func (mb *manifestBuilder) addLockedOutputs(po *preparedLockedOutputs) *manifestBuilder {
	if po == nil {
		return mb
	}
	mb.lockedOutputs.distributions = append(mb.lockedOutputs.distributions, po.distributions...)
	mb.lockedOutputs.coins = append(mb.lockedOutputs.coins, po.coins...)
	mb.lockedOutputs.states = append(mb.lockedOutputs.states, po.states...)
	return mb
}

func (mb *manifestBuilder) addInfoStates(infoDistribution identityList /* single for all these states */, infoStates ...*prototk.NewState) *manifestBuilder {
	for _, infoState := range infoStates {
		mb.infoDistributions = append(mb.infoDistributions, infoDistribution)
		mb.infoStates = append(mb.infoStates, infoState)
	}
	return mb
}

func (mb *manifestBuilder) addLockInfo(lockInfo *preparedLockInfo) *manifestBuilder {
	mb.lockInfo = lockInfo
	return mb
}

func (mb *manifestBuilder) finalizeNewState(manifest *types.NotoManifest, newState *prototk.NewState, distribution identityList) error {
	stateID, err := pldtypes.ParseBytes32(*newState.Id)
	if err == nil {
		manifest.States = append(manifest.States, &types.NotoManifestStateEntry{
			ID:           stateID,
			Participants: distribution.addresses(),
		})
	}
	return err
}

func (mb *manifestBuilder) buildManifest(ctx context.Context, stateQueryContext string) (*prototk.NewState, error) {

	// Build a list of all the new states which do not have an ID allocated
	totalStateCount := len(mb.infoStates) + len(mb.outputs.states) + len(mb.lockedOutputs.states) + 1
	newStatesWithNoID := make([]*prototk.NewState, 0, totalStateCount)
	addIfNoID := func(states ...*prototk.NewState) {
		for _, s := range states {
			if s.Id == nil {
				newStatesWithNoID = append(newStatesWithNoID, s)
			}
		}
	}
	addIfNoID(mb.infoStates...)
	addIfNoID(mb.outputs.states...)
	addIfNoID(mb.lockedOutputs.states...)
	if mb.lockInfo != nil {
		addIfNoID(mb.lockInfo.state)
	}

	// Allocate state IDs in Paladin for all the new states
	err := mb.n.allocateStateIDs(ctx, stateQueryContext, newStatesWithNoID)
	if err != nil {
		return nil, err
	}

	// Build the manifest object
	manifest := &types.NotoManifest{
		Salt:   pldtypes.RandBytes32(),
		States: make([]*types.NotoManifestStateEntry, 0, totalStateCount),
	}
	var fullDistribution identityList
	for i, infoState := range mb.infoStates {
		if err == nil {
			fullDistribution = append(fullDistribution, mb.infoDistributions[i]...)
			err = mb.finalizeNewState(manifest, infoState, mb.infoDistributions[i])
		}
	}
	for i := range mb.outputs.states {
		if err == nil {
			fullDistribution = append(fullDistribution, mb.outputs.distributions[i]...)
			err = mb.finalizeNewState(manifest, mb.outputs.states[i], mb.outputs.distributions[i])
		}
	}
	for i := range mb.lockedOutputs.states {
		if err == nil {
			fullDistribution = append(fullDistribution, mb.lockedOutputs.distributions[i]...)
			err = mb.finalizeNewState(manifest, mb.lockedOutputs.states[i], mb.lockedOutputs.distributions[i])
		}
	}
	if mb.lockInfo != nil && err == nil {
		fullDistribution = append(fullDistribution, mb.lockInfo.distribution...)
		err = mb.finalizeNewState(manifest, mb.lockInfo.state, mb.lockInfo.distribution)
	}
	if err != nil {
		return nil, err
	}
	return mb.n.makeNewManifestInfoState(manifest, fullDistribution.identities() /* note this de-dups */)
}
